### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by talopakola** [DuskieWhy/exe-2.5-code#18]
### Describe your problem here.

ehhhh, i'm having this error when trying to compile
(I used google translator sorry lol)

![Screenshot_4](https://user-images.githubusercontent.com/127637820/231022336-4b653070-9df8-4de2-a4d6-eae85e6f97fc.png)

I fixed an error I was getting, but these I couldn't fix :(

(I used google translator :D)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
use flixel 4.11.0 and flixel addons 2.11.0

**Comment by talopakola** [comment]
can you please send me the code to do this?
(Google translator)

**Comment by moxie-coder** [comment]
`haxelib install flixel 4.11.0`
`haxelib install flixel-addons 2.11.0`

**Comment by talopakola** [comment]
still with the same error :(

**Comment by moxie-coder** [comment]
you have to make sure it _is_ using those versions via
`haxelib set flixel 4.11.0`
`haxelib set flixel-addons 2.11.0`

**Comment by talopakola** [comment]
it worked bro, thanks a lot :)

**Comment by moxie-coder** [comment]
you're welcome :)
btw don't forget to close the issue please

**Comment by talopakola** [comment]
ok
