### ISSUE TITLE
Compiling the source code

### ISSUE THREAD

**Issue by Rolee0707** [DuskieWhy/exe-2.5-code#19]
### Describe your problem here.

I tried several tutorials, nothing works, I get the same error:
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/FlxBasic.hx:201: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:680: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:688: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tweens/FlxTween.hx:24: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/FlxInput.hx:84: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tile/FlxBaseTilemap.hx:1382: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirectionFlags.hx:8: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirection.hx:7: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/keyboard/FlxKey.hx:8: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/mouse/FlxMouseButton.hx:85: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/gamepad/FlxGamepadInputID.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/text/FlxText.hx:1153: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/actions/FlxActionInputAnalog.hx:17: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/actions/FlxActionInputAnalog.hx:393: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/FreeplayState.hx:78: characters 57-58 : Int should be flixel.util.FlxAxes
source/FreeplayState.hx:78: characters 57-58 : ... For optional function argument 'repeatAxes'
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/PlayState.hx:1552: lines 1552-1585 : Warning : (WUnusedPattern) This case is unused
source/PlayState.hx:1667: characters 78-84 : Warning : (WUnusedPattern) This pattern is unused
source/PlayState.hx:7956: characters 78-81 : Warning : (WUnusedPattern) This pattern is unused

(I got this when I installed this: haxelib set flixel 4.11.0)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by moxie-coder** [comment]
your flixel addons is too new

**Comment by Rolee0707** [comment]
> your flixel addons is too new

Which version do you recommend?

**Comment by moxie-coder** [comment]
> > your flixel addons is too new
> 
> Which version do you recommend?

2.11.0 for flixel 4.11.0

**Comment by Rolee0707** [comment]
> > > your flixel addons is too new
> > 
> > 
> > Which version do you recommend?
> 
> 2.11.0 for flixel 4.11.0

thank you, it worked
