### ISSUE TITLE
Encore doesn't load

### ISSUE THREAD

**Issue by Rolee0707** [DuskieWhy/exe-2.5-code#20]
### Describe your problem here.

Im trying to load encore mode, but i got a message, that i got when i loaded up the game too. The EncoreState.hx file says this:

package;

import flixel.util.FlxTimer;
import flixel.input.gamepad.FlxGamepad;
import flash.text.TextField;
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.addons.display.FlxGridOverlay;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.group.FlxSpriteGroup.FlxTypedSpriteGroup;
import flixel.addons.transition.FlxTransitionableState;
import flixel.math.FlxMath;
import flixel.text.FlxText;
import flixel.util.FlxColor;
import flixel.tweens.FlxEase;
import flixel.tweens.FlxTween;
import lime.utils.Assets;

#if windows
import Discord.DiscordClient;
#end

using StringTools;

class EncoreState extends MusicBeatState // REWRITE FREEPLAY!?!?!? HELL YEA!!!!!
{

	public static var talk:FlxText;

	override function create()
	{
		talk = new FlxText();
		talk.text = "I wish I could've made a bigger impact to this team.\nI really did kinda feel like a wasted slot, everyone else around me being much more skilled and whatnot.\nI do miss the team, I miss the progress it made. I miss it a lot.\nTeam did feel like a family, despite everything that happened.\nI figured a message like this would appear from someone like me in this state,\nconsidering its the one that people went after me for.\nThe story portraits were not by divide, they were by scorch, only triple trouble's portrait had a concept by divide.\nRegardless, if I had known divide had a hand in their creation, i wouldnt had laid a finger on them. I am beyond sorry.\nI hope exe finally falls and rots like it should.\nRest in peace to the dream that was exe mod, and let anything that tries to recreate it, rot. just like the real mod.\n \n-DuskieWhy";
		talk.alignment = CENTER;
		talk.scale.set(2.3,2.3);
		talk.updateHitbox();
		talk.screenCenter();
		add(talk);
		super.create();
	}
	

	override function update(elapsed:Float)
	{
		super.update(elapsed);

		if(controls.ACCEPT)
			MusicBeatState.switchState(new MainMenuState());
	}
}

Is there any code for the actual encore mode?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by moxie-coder** [comment]
because it’s not finished obviously, and that’s a message from Duskiewhy, one of the mods coders

**Comment by Rolee0707** [comment]
> because it’s not finished obviously, and that’s a message from Duskiewhy, one of the mods coders

Ohh, okay. Does anyone have a code for it tho? Like a fanmade or something

**Comment by moxie-coder** [comment]
> > because it’s not finished obviously, and that’s a message from Duskiewhy, one of the mods coders
> 
> Ohh, okay. Does anyone have a code for it tho? Like a fanmade or something

not that I know of, but you could look around on GitHub

**Comment by Rolee0707** [comment]
> > > because it’s not finished obviously, and that’s a message from Duskiewhy, one of the mods coders
> > 
> > 
> > Ohh, okay. Does anyone have a code for it tho? Like a fanmade or something
> 
> not that I know of, but you could look around on GitHub

I do that.
Also sorry if the questions are too much, but story mode doesnt work. if i press enter on too slow, a red square just flashes, the song doesnt start.
do you know  to fix it?

**Comment by talopakola** [comment]
Edit: Sorry, I made a mistake, but simply search another source code and copy the Encore menu from there, it's not difficult, just search.

**Comment by Rolee0707** [comment]
> Edit: Sorry, I made a mistake, but simply search another source code and copy the Encore menu from there, it's not difficult, just search.

I already found one, thanks tho
