### ISSUE TITLE
Video playing issue

### ISSUE THREAD

**Issue by Rolee0707** [DuskieWhy/exe-2.5-code#21]
### Describe your problem here.

Im trying to add videos to the sound test menu (maybe cutscenes later) and I tried to use the 2.0 source code because that uses videos, when i tried to add a sound test video, it says this:

MP4Handler has no field playMP4

the code from 2.0: 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by Rolee0707** [comment]
Sorry I accidently posted the issue without the code

so here it is the sound test video from 2.0:

else if (first == 23 && second == 23) 
			{
				var video:MP4Handler = new MP4Handler();
				woahmanstopspammin = false;
				flashyWashy(true);
				new FlxTimer().start(2, function(tmr:FlxTimer)
				{
					flashyWashy(false);
					FlxG.sound.music.stop();
	
				});
				new FlxTimer().start(2.1, function(tmr:FlxTimer)
				{
                	video.playMP4(Paths.video('soundtestvideoname'));
					incameo = true;
				});

**Comment by moxie-coder** [comment]
it's `playVideo` not `playMP4`

**Comment by Rolee0707** [comment]
> it's `playVideo` not `playMP4`

ok, it works now, thank you!

**Comment by moxie-coder** [comment]
np
