### ISSUE TITLE
Static Notes not working

### ISSUE THREAD

**Issue by KalashniPepsi** [DuskieWhy/exe-2.5-code#3]
### What is your question?

Before you say anything, i asked on the Psych engine Issues board on how to make notes functionally similar to the Static Notes and ShadowMario just told me to go here. If this is the wrong place to ask then idk what the hell im supposed to do.

tl;dr Anyone know how to fix the Static Notes? been at it for a few days and i don't see why this is an issue.

**Comment by MemeHoovy** [comment]
I'm pretty sure duskie is not gonna fix it, he doesn't wanna work on this mod anymore

**Comment by KalashniPepsi** [comment]
> I'm pretty sure duskie is not gonna fix it, he doesn't wanna work on this mod anymore

yeah i know that, but like if anyone else sees this maybe they can offer a solution or some tips. Im not expecting an answer from Duskie, i just want an answer in general

**Comment by duckiewhy** [comment]
suck my ballz

**Comment by MemeHoovy** [comment]
> suck my ballz

kisma

**Comment by KalashniPepsi** [comment]
> suck my ballz

fair enough

**Comment by TheKitBoi** [comment]
now
do it
![close the dam issue](https://user-images.githubusercontent.com/84044666/199781649-fd1ef59e-e799-436b-a9f3-1fceeb5c1bf4.gif)

**Comment by KalashniPepsi** [comment]
> now do it ![close the dam issue](https://user-images.githubusercontent.com/84044666/199781649-fd1ef59e-e799-436b-a9f3-1fceeb5c1bf4.gif) [ ![close the dam issue](https://user-images.githubusercontent.com/84044666/199781649-fd1ef59e-e799-436b-a9f3-1fceeb5c1bf4.gif) ](https://user-images.githubusercontent.com/84044666/199781649-fd1ef59e-e799-436b-a9f3-1fceeb5c1bf4.gif) [ ](https://user-images.githubusercontent.com/84044666/199781649-fd1ef59e-e799-436b-a9f3-1fceeb5c1bf4.gif)

you made a gif just for this? damn

**Comment by KalashniPepsi** [comment]
Update: nvm i got it l0l

**Comment by REALHaydenGaming** [comment]
> suck my ballz

bro actually roasted the shit out of someone your an sigma chad frrrrrrr.
