### ISSUE TITLE
is there a way to enable the sound test

### ISSUE THREAD

**Issue by Tuxitoz** [DuskieWhy/exe-2.5-code#9]
### Describe your problem here.

all the code seems to be there, tho idk how to enable it
if its even possible in the first place to enable the source code, then please say it here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not yet

**Comment by MemeHoovy** [comment]
by playing through the mod normally, no

**Comment by Tuxitoz** [comment]
> by playing through the mod normally, no

i meant if i could enable it through the source code of the mod

**Comment by MemeHoovy** [comment]
it should, but it doesn't work for some reason

**Comment by Tuxitoz** [comment]
> it should, but it doesn't work for some reason

oh, so even if you try to enable it through the source code (like with editing the SoundTestMenu.hx file), it still won't work?

**Comment by MemeHoovy** [comment]
no, look at this code here
`
						FlxG.save.data.weekCompleted = StoryMenuState.weekCompleted;
						ClientPrefs.beatweek = true;
						ClientPrefs.saveSettings();
						FlxG.save.flush();
`

**Comment by Tuxitoz** [comment]
> no, look at this code here `FlxG.save.data.weekCompleted = StoryMenuState.weekCompleted; ClientPrefs.beatweek = true; ClientPrefs.saveSettings(); FlxG.save.flush();` it's suppost to unlock sound test, but it doesn't work for some reason

oh

**Comment by liamp0924** [comment]
2 year late lol but download this file put it into source and if prompted to replace it replace it [https://drive.google.com/file/d/1jMvPuWlI2dNn-xbGR4DUj_OjIrNL0uD-/view?usp=sharing](url)
